# Generated by Django 4.2 on 2023-05-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    # models.py de oluşturduğumuz modeli database'in anlayacağı bir formata dönüştürüyor
    # ayrıca her elemana kendi random bir id de oluşturuyor

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
